version: "3.7"
services:
  app:
    image: wiley19/to-do-list:1  # Use your Docker Hub username and tag
    build: .  # This tells Docker Compose to build the image from the Dockerfile in the current directory
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_DB: todo-db

  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: todo-db

volumes:
  todo-mysql-data:
