version: "3.7"
services:
  app:
    image: node:16.14
    command: sh -c "yarn install && yarn run dev" 
    ports:
      - 3000:3000
    working_dir: /app
    volumes: 
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_DB: todo-db

  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: todo-db
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/prometheus.yml'
    ports:
      - '9090:9090'

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - '9100:9100'

  grafana:
    image: grafana/grafana
    ports:
      - "4000:3000"
  
volumes:
  todo-mysql-data:
